# _config.yml

# required, replace with your own information -----
title: David Thai Portfolio
author: David Thai
description: > 
  A portfolio of my student work during my time at Clemson University
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
#---------------------------------------------------

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

